### PR TITLE
attempting to right align some of the new footer to the header

### LINKED ISSUE #307: Align the bottom-most "princeton university" logo with the right-most element of the header
### Current display
Screenshot 2024-08-05 at 9 13 21 AM

### Desired display

Provide some consistency in right alignment to allow the header and footer to frame the page. maybe by pulling the princeton university logo further to the right.

(Note this is a departure from the new library site's footer, which doesn't have anything as far to the right as its header.)

### Acceptance criteria

- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

### PR DESCRIPTION
**Pull request by JaymeeH**
closes #307

### CODE REVIEW

**Review by christinach — CHANGES_REQUESTED** [review]
@JaymeeH I don't think we want to push  the content of the footer to the right. 
 
### current display of the footer in production:
Footer in production

### With changes from this PR:
Footer display PR#339

**Comment by JaymeeH** [comment]
@christinach Thanks for the review — you're right, we shouldn't push the content. It looked a bit different when I was looking at it locally. I'm going to spend some more time playing around with the alignment instead of padding/margins. Also, are you viewing the header and footer through lux locally or are you pulling the components into a different application/empty page to see them on top of each other like this?

**Comment by christinach** [comment]
> @christinach Thanks for the review — you're right, we shouldn't push the content. It looked a bit different when I was looking at it locally. I'm going to spend some more time playing around with the alignment instead of padding/margins. Also, are you viewing the header and footer through lux locally or are you pulling the components into a different application/empty page to see them on top of each other like this?

@JaymeeH I use the allsearch which is a vue app https://github.com/pulibrary/allsearch_frontend/. you can clone it and `yarn install` then follow the documentation [how to use a local copy](https://github.com/pulibrary/lux-design-system?tab=readme-ov-file#using-a-local-copy-of-lux-design-system-in-your-project). 
Then from the dev tools I remove the `page-wrap` element which wraps the main part of the page so that I have only the header and the footer on my screen.

- Also when you review the changes consider having the page in the [max-width](https://github.com/pulibrary/lux-design-system/blob/13378f7d51c5dfdcbcb8d22238a535f6be68800d/src/components/LuxLibraryFooter.vue#L242) which is 1440px. (you don't want to change this number in the code)

- Regarding the alignment if the intention is to move the library links(for Library Staff, Staff Directory etc..) to the right I would look into changing the `.lux-library-links ul` to have `align-content: right` . It is a flex item. Then I would consider adding right padding on this ul and only if it's needed. 

- I would also ask @beth-german for this change because the footer is used in the [allsearch](https://allsearch.princeton.edu/?q=book) which is part of the library website. 

I've added some more recent screenshots on the ticket.

**Comment by christinach** [comment]
@JaymeeH I'm also suggesting to use the allsearch and not a rails app because the rails apps in the library usually use bootstrap. Bootstrap has a different max-width on specific screen sizes. So it makes it difficult to adjust the lux design system following what you see on the rails app.

**Comment by JaymeeH** [comment]
@christinach Thanks for the tips! Should help to gauge UI changes more easily

**Comment by JaymeeH** [comment]
@christinach I used `align-content: end` instead of right because `left/right` seem to be deprecated on edge browsers at least, and that may also be true for firefox browsers. Also including two screenshots to show right alignment with and without padding — I guess now I would ask Beth German which they prefer?

Right Aligned footer with no padding:

Right Align, No padding


Right Aligned footer with `2rem` right-padding:

Right Align, 2rem right padding

**Comment by christinach** [comment]
@JaymeeH can you also make sure that in the small screen it will have the left alignment? Thanks!

**Comment by christinach** [comment]
@beth-german can you please review the two screenshots above?

**Comment by beth-german** [comment]
I think it looks a bit better with the 2rem right padding.

**Review by christinach — COMMENTED** [review]
@JaymeeH following @beth-german 's review can you uncomment the right-padding so that I can I approve it?

**Review by christinach — APPROVED** [review]
Thanks @JaymeeH !

**Pull request merged**
