### PR TITLE
Create a new University Privacy notice component. Import it in the Library Footer

### PR DESCRIPTION
**Pull request by christinach**
[LuxUniversityPrivacyNotice] Create new component for University Privacy notice
[LuxLibraryFooter] Import LuxUniversityPrivacyNotice in the Library Footer; 
[LuxLibraryFooter] Remove margin-right so that in large screens the new link doesn't wrap the external icon

Library Footer screenshot

### CODE REVIEW

**Review by maxkadel — COMMENTED** [review]
Would it be possible to handle the line break with either a non-breaking space or something like [white-space: nowrap](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space), so that we don't have to change the width properties??

**Comment by christinach** [comment]
> Would it be possible to handle the line break with either a non-breaking space or something like [white-space: nowrap](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space), so that we don't have to change the width properties??

@maxkadel which line break do you refer to?

**Comment by christinach** [comment]
> Would it be possible to handle the line break with either a non-breaking space or something like [white-space: nowrap](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space), so that we don't have to change the width properties??

If you are talking about the line where I remove the 'margin-right', this will not change the width at all. 
I added the margin-right so that the library flex links will be pushed a little bit to the right and they are aligned with the Library logo at the bottom.

**Review by maxkadel — APPROVED** [review]
Looks good! Thanks @christinach! 🐬

**Pull request merged**
